worker:
  name: IaasAdpBizAdmin
  maxTaskThreadNum: 100
  accessControlAllowOrigin: '*'
  admin:
    host: 127.0.0.1
    port: 9110
    nodeType: JOB_TRACKER
    registry: multicast
    registryAddress: 192.168.10.2:2181
    remotingNetworkManager: netty
    remotingServiceClient: tcp
    group: {name: cloudcareWorkerGroup, instance: worker}
  server: {host: 0.0.0.0, port: 8110, webContext: null}

aliyun:
  accessKeyId: KmFGzxgmfxnWMTNk
  accessKeySecret: zg0VDtgoshk623weWP1TqTSQCyBqfa
  request:
    hasProxy: true
    connectionTimeout: 60000
    readTimeout: 60000
    maxThread: 10